/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const customaws = {
    identityPoolId: "eu-central-1:62a6f9a0-fc6e-4969-a313-8c3fe49996a4",
    identityPoolRegion: "eu-central-1",
    region: "eu-central-1",
    userPoolId: "eu-central-1_6oE2NvLU1",
    userPoolWebClientId: "39ien2pcmu4j9t0ept17e9ja6e",
    graphQlEndpoint: "https://a6qd64utujb4lk5r5y2qriijge.appsync-api.eu-central-1.amazonaws.com/graphql",
    mainGraphQLAuthenticationMethod: "AWS_IAM"
}

const customaws2 = {
    identityPoolId: "eu-west-1:fda07a76-6269-4974-b353-8478d14c95ab",
    identityPoolRegion: "eu-west-1",
    region: "eu-west-1",
    userPoolId: "eu-west-1_opQnUZ1VY",
    userPoolWebClientId: "h4noj9f3ds7b2erhrrqku92ii",
    graphQlEndpoint: "https://k3pn5iwvnfhwznajxtfh3y47ka.appsync-api.eu-west-1.amazonaws.com/graphql",
    mainGraphQLAuthenticationMethod: "AMAZON_COGNITO_USER_POOLS"
}

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:fda07a76-6269-4974-b353-8478d14c95ab",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_opQnUZ1VY",
    "aws_user_pools_web_client_id": "h4noj9f3ds7b2erhrrqku92ii",
    "oauth": {
        "domain": "betsby-research.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "betsby://",
        "redirectSignOut": "betsby://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "betsbyREST",
            "endpoint": "https://ngjwfbbthi.execute-api.eu-west-1.amazonaws.com/research",
            "region": "eu-west-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://k3pn5iwvnfhwznajxtfh3y47ka.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "ours3-research",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_content_delivery_bucket": "oureality-20190919212533-hostingbucket-research",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d2ij74qlzgyj7r.cloudfront.net",
    "Auth": {}
};


export default customaws;
